version: "{build}"

platform:
  - x64

install:
  - cinst wget
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem
  - set SSL_CERT_FILE=C:\cacert.pem

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\consul
  - download.bat
  - cpack consul.nuspec

test:
  - cinst consul -source %APPVEYOR_BUILD_FOLDER%\consul
  - cuninst consul

deploy: off
