version: 0.9.2.{build}

environment:
  TOKEN:
    secure: 3sxpbbTFvPJlNQ7fwBDGM6EkuisTVEnALEK9Krtx5zAOvXdaIo+jCql4ms7cyFyj

platform:
  - x64

install:
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem

build_script:
  - ps: >-
      $env:CONSUL_VERSION = ($env:APPVEYOR_BUILD_VERSION | ? {$_ -match('^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-rc\d+)?')} | select @{L="Matches";E={$matches[0]}}).matches;
      cmd /c download.bat;
      choco pack consul.nuspec

test_script:
  - ps: cinst consul -fdvy -source "$pwd;http://chocolatey.org/api/v2/"
  - ps: cuninst -fdvy consul
  - ps: cinst consul -fdvy -source "$pwd;http://chocolatey.org/api/v2/" -params '-bind=127.0.0.1'
  - ps: cuninst -fdvy consul

deploy_script:
  - ps: >-
      Write-Host $env:APPVEYOR_REPO_TAG;
      if($env:APPVEYOR_REPO_BRANCH -eq 'master' -And $env:APPVEYOR_REPO_TAG -eq 'true') {
        $version = $env:APPVEYOR_BUILD_VERSION -replace('\.[^.\\/]+$');
        choco apiKey -k $env:TOKEN -source https://push.chocolatey.org/;
        choco push consul.$version.nupkg
      }

artifacts:
  - path: '**\*.nupkg'
